### ISSUE TITLE
Simutrans OTRP on Steam

### ISSUE THREAD

**Issue by Roboron3042** [teamhimeh/simutrans#44]
Hello Simutrans OTRP developers. I'm Roboron, the current (and new) maintainer of Simutrans on Steam. As part of my plans as a new maintainer, I planned to bring Simutrans OTRP to Steam players (available as a beta branch). However, before doing so, I need to solve some issues related to Simutrans OTRP.

1. **Delete GDPR incompatible code**. I can't prevent users on Europe from playing, so we need to comply with EU laws. I have taken a look at the code and I think relevant, non-GDPR compatible code was added in this commit: https://github.com/aburch/simutrans/commit/1b2a0415b3e1df800aba9c75bb57c907659b4c1c
Please confirm me this, so I can compile a Steam version without incompatible GDPR code.

2. **Redistribution of pak files**. In the README it is stated that OTRP needs some extra pak files ( https://drive.google.com/open?id=0B_rSte9xAhLDanhta1ZsSVcwdzg ). But it is unclear to me under what license are those files, and if I can redistribute them to Steam users without problem. A clear permission would be very appreciated.

3. **Your consent**. Even if the AL allows me to redistribute OTRP on Steam, I prefer not to do that if project creators don't agree with this...

Regards, Roboron.

**Comment by teamhimeh** [comment]
I welcome your distribution plan of OTRP on Steam, but first of all, I may stop the development of OTRP as I start my full-time job in next April. Distributing OTRP on Steam may need some technical support for players, but there is no guarantee that we can provide a support for a long period. Please consider this matter when you decide distributing OTRP on Steam.

I answer to your questions below...

1. Collecting usage data is just for my interest and it's time to delete the code to make it GDPR compatible. I will do that in the next release, which should be released in a few weeks.
1. I'm asking about this to the author of Ribi-Arrow pak files. I will notify you when I got the answer from him.
1. I agree to the distribution of OTRP on Steam, as long as you consider the risk that I may not be able to provide any updates and supports in the future due to my coming full-time job.

**Comment by teamhimeh** [comment]
Sorry for taking a long time. I uploaded the version in which the log sender was removed as [OTRP-Steam branch](https://github.com/teamhimeh/simutrans/tree/OTRP-Steam). This branch is based on OTRP v28_3, which is based on r9281.

**Comment by Roboron3042** [comment]
Good news, thank you. What about the author of Ribi-Arrow pak files? Any update?

**Comment by Roboron3042** [comment]
Simutrans OTRP is now available from Steam selecting Properties -> Betas -> otrp
